# Generated by Django 5.0.1 on 2024-01-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipeproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeproduct',
            name='weight_in_grams',
            field=models.IntegerField(default=0),
        ),
    ]
